[package]
name = "gambit"
version = "0.1.0"
edition = "2021"
authors = ["Chandrakana Nandi <chandra@certora.com>", "Steve Wilson <steve@certora.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.7", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
env_logger = { version = "0.7", default-features = false }
rand_pcg = "0.2"
rand = { version = "0.7", default-features = false, features = ["std"] }
itertools = "0.10.5"