name: Gambit

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo bin
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
      - name: Build and Test
        run: make
      - name: Rename gambit binary
        run: mv ./target/release/gambit ./target/release/gambit-${{ github.ref_name }}
        if: startsWith(github.event.ref, 'refs/tags/v') # only on new tag creation
      - name: Upload artifact to action
        uses: actions/upload-artifact@v3
        if: startsWith(github.event.ref, 'refs/tags/v') # only on new tag creation
        with:
          name: gambit-${{ github.ref_name }}
          path: ./target/release/gambit-${{ github.ref_name }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.event.ref, 'refs/tags/v') #  only on new tag creation
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gambit-${{ github.ref_name }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "gambit-${{ github.ref_name }}"
          allowUpdates: true
          name: Release ${{ github.ref_name }}