name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache cargo bin
      uses: actions/cache@v2
      with:
        path: ~/.cargo/bin
        key: ${{ runner.os }}-cargo-bin
    - name: Build and Unit Test
      run: |
        cargo fmt
        cargo clippy
        cargo test --release
      
  regression:
    name: Regression Tests
    run: |
      cargo run --release -- mutate  --filenames benchmarks/Delegation/DelegationExample.sol --solc solc8.13
      cargo run --release -- mutate  --filenames benchmarks/10Power/TenPower.sol