name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo bin
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
      - uses: Swatinem/rust-cache@v1
      - name: Build and Unit Test
        run: |
          cargo fmt
          cargo clippy
          cargo test --release
