name: Gambit

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo bin
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
      - name: Install solc for sanity checks
        run: |
              if [[ ! -f "/usr/bin/solc" ]]
              then
                wget -q https://github.com/ethereum/solidity/releases/download/v0.8.13/solc-static-linux 
                mv solc-static-linux solc
                chmod +x solc
                sudo mv solc /usr/bin/solc
              fi
      - name: Build and Test
        run: make
      - name: Rename gambit binary
        run: mv ./target/release/gambit ./target/release/gambit-$TAG
        if: startsWith(github.event.ref, 'refs/tags/v') # only on new tag creation
      - name: Upload artifact to action
        uses: actions/upload-artifact@v3
        if: startsWith(github.event.ref, 'refs/tags/v') # only on new tag creation
        with:
          name: gambit-${{ env.TAG }}
          path: ./target/release/gambit-${{ env.TAG }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.event.ref, 'refs/tags/v') #  only on new tag creation
    env:
      TAG: ${{ github.ref_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gambit-${{ env.TAG }}
      - name: Create a release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          release_exist=$(gh release view $TAG 2>&1 || exit 0)
          if [ "$release_exist" = "release not found" ]; then
            gh release create $TAG gambit-$TAG --title "Release $TAG" --generate-notes --latest
          else
            gh release upload $TAG gambit-$TAG
          fi